### ISSUE TITLE
Stack?

### ISSUE THREAD

**Issue by Anahkiasen** [yorkcommatyler/prouning#1]
Did you have anything in mind for the stack? Was thinking something light and easy to maintain like a [create-react-app](https://github.com/facebookincubator/create-react-app) app using the [markov-strings](https://www.npmjs.com/package/markov-strings) package but that's for a JS/React app, not sure what stack you had in mind (maybe something completely different?)

**Comment by yorkcommatyler** [comment]
@Anahkiasen I didn't yet! Like I mentioned, I have almost no backed experience, so this should be a fun (hopefully not irritating for you) learning experience. I've always wanted a reason to learn MEAN, mainly because I know JS, but that may be overkill. Never worked with React, but definitely willing to dive in headfirst if you think it's doable!

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Anahkiasen** [comment]
Aight, I'll see if I can make a small setup PR with a basic working prototype

**Comment by yorkcommatyler** [comment]
@Anahkiasen Great, I'm working on a landing page with info now as well.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Anahkiasen** [comment]
I'll need git access, you can invite me as collaborator in the settings of the repo

**Comment by yorkcommatyler** [comment]
@Anahkiasen yep, I'll add you as soon as I get home!

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
